[package]
name = "ugc-scraper"
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

[dependencies]
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread", "rt"] }
reqwest = "0.11.22"
scraper = "0.18.1"
miette = "5.10.0"
thiserror = "1.0.50"
main_error = "0.1.2"
time = { version = "0.3.30", features = ["parsing", "macros"] }
steamid-ng = "1.0.0"