[package]
name = "ugc-scraper-types"
version = "0.1.0"
edition = "2021"

[dependencies]
steamid-ng = "1.0.0"
serde = { version = "1.0.215", features = ["derive"], optional = true }
time = { version = "0.3.36", features = ["parsing", "macros"] }

[features]
serde = ["dep:serde", "time/serde", "time/formatting"]
default = ["serde"]
